### ISSUE TITLE
Is there any requirement for the node version of this project?

### ISSUE THREAD

**Issue by oeyoews** [TiddlyWiki/MultiWikiServer#7]
![Image](https://github.com/user-attachments/assets/d4465e73-66d3-4c31-bb5e-5db8d2038670)

![Image](https://github.com/user-attachments/assets/c3111dad-3bce-401d-bfc2-25abf1c6c2fc)

I tried 23.5 and 16.8 and they both don't work

**Comment by Arlen22** [comment]
Interesting. I'm using v18.20.5. You might also try deleting node_modules and rerunning npm install after you switch versions. 

It looks like both of these errors are esbuild related, which is used by tsx. tsx is definitely temporary.

**Comment by oeyoews** [comment]
It seems that there is something wrong with the path on windows. (I use npm init @tiddlywiki/mws@latest mws)

![Image](https://github.com/user-attachments/assets/a622d956-86f1-420b-b65f-bc28a19eca2e)

**Comment by Arlen22** [comment]
@oeyoews Fixed. Good catch. You can `npm install @tiddlywiki/mws@latest` and try again.

**Comment by oeyoews** [comment]
![Image](https://github.com/user-attachments/assets/efa6a5de-8501-4254-8fd4-30b960ab331d)

I see some undefined values ​​in the logs, is this normal? It looks weird.

**Comment by Arlen22** [comment]
> I see some undefined values ​​in the logs, is this normal? It looks weird.

Good catch. I just pushed a fix for that.

**Comment by oeyoews** [comment]
![Image](https://github.com/user-attachments/assets/ab2d3364-4378-4ef5-a9ee-e17f0db9b50a)

![Image](https://github.com/user-attachments/assets/1ee2cb1a-f94d-4af4-8562-b6172188aa95)
These problems are still encountered in the development environment

**Comment by Arlen22** [comment]
The first one is just a warning for the time being. 

The second one is puzzling. Is that command being run on Windows, Linux, or WSL (1 or 2)?
